version: '2'
services:
  web:
    build: ./web
    ports:
     - "8080:80"
    volumes:
     - ./web/code:/var/www/html/
     - ./web/logs:/var/log/apache2
    links:
      - api
    # depends_on:
    #  - api
  api:
    build: ./api
    ports:
      - "8888:8888"
    volumes:
      - ./api/code:/opt/csynapse
    links:
      - db
      - queue
      - mongo
      - memcached
    depends_on:
      - db
      - queue
      - mongo
      - memcached
  db:
    build: ./db
    ports:
      - "3306:3306"
  queue:
    image: rabbitmq
    hostname: csynapse_queue
  tasks:
    build: ./tasks
    links:
      - mongo
      - queue
      - db
    volumes:
      - ./tasks/code:/opt/csynapse
  mongo:
    image: mongo
    volumes:
      - ./mongo/db:/data/db
    ports:
      - "27017:27017"
  memcached:
    image: memcached
  inside:
    image: ubuntu
    entrypoint: /bin/bash
    links:
      - db
      - queue
      - mongo
      - memcached
      - web
      - api
      - tasks
