version: '2'
services:
  web:
    build: ./web
    ports:
     - "8080:80"
    volumes:
     - ./web/code:/var/www/html/
     - ./web/logs:/var/log/apache2
    links:
      - api
    # depends_on:
    #  - api
  api:
    build: ./api
    ports:
      - "8888:8888"
    volumes:
      - ./api/code:/opt/csynapse
    links:
      - queue
      - mongo
      - memcached
    depends_on:
      - queue
      - mongo
      - memcached
      - tasks
  queue:
    image: rabbitmq
    hostname: csynapse_queue
  tasks:
    build: ./tasks
    links:
      - mongo
      - queue
    volumes:
      - ./tasks/code:/opt/csynapse
  mongo:
    image: mongo
   volumes:
     - ./mongo/db:/data/db
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo
  memcached:
    image: memcached
  inside:
    image: ubuntu
    entrypoint: /bin/bash
    links:
      - queue
      - mongo
      - memcached
      - web
      - api
      - tasks
