CREATE DATABASE csynapse;
USE csynapse;
CREATE USER 'csynapse'@'localhost' IDENTIFIED BY 'MyMZhdiEvY33WbqqAsFnLkcoQqRbacxo';
CREATE USER 'csynapse'@'%' IDENTIFIED BY 'MyMZhdiEvY33WbqqAsFnLkcoQqRbacxo';
GRANT ALL PRIVILEGES ON csynapse.* TO 'csynapse'@'localhost';
GRANT ALL PRIVILEGES ON csynapse.* TO 'csynapse'@'%';
FLUSH PRIVILEGES;
CREATE TABLE Algorithms (identifier VARCHAR(32) NOT NULL, description VARCHAR(100), active BOOLEAN, PRIMARY KEY(identifier));
CREATE TABLE Requests (identifier CHAR(32) NOT NULL, algorithm VARCHAR(25) NOT NULL, computing BOOLEAN DEFAULT 0, complete BOOLEAN DEFAULT 0, return_object LONGTEXT, last_update TIMESTAMP, PRIMARY KEY (identifier, algorithm), FOREIGN KEY (algorithm) REFERENCES Algorithms(identifier));
CREATE TABLE RequestInformation (identifier CHAR(32) NOT NULL, description VARCHAR(200) NOT NULL, mongo_id CHAR(24), PRIMARY KEY (identifier), FOREIGN KEY (identifier) REFERENCES Requests(identifier));
INSERT INTO Algorithms (identifier, description, active) VALUES ('Test', 'Test Algorithm', 1);
INSERT INTO Algorithms (identifier, description, active) VALUES ('adaBoost', 'Adaboost with Decision Trees', 1);
INSERT INTO Algorithms (identifier, description, active) VALUES ('decisionTree', 'Decision Tree', 1);
INSERT INTO Algorithms (identifier, description, active) VALUES ('graphData', 'Training data into data points', 0);
INSERT INTO Algorithms (identifier, description, active) VALUES ('guassNB', 'Gaussian NaiveBayes', 1);
INSERT INTO Algorithms (identifier, description, active) VALUES ('knearest', 'Nearest Neighbors', 1);
INSERT INTO Algorithms (identifier, description, active) VALUES ('nearestCentroid', 'Nearest Centroid', 1);
INSERT INTO Algorithms (identifier, description, active) VALUES ('passiveAggressive', 'Passive Aggressive Classifier', 1);
INSERT INTO Algorithms (identifier, description, active) VALUES ('perceptron', 'Perceptron', 1);
INSERT INTO Algorithms (identifier, description, active) VALUES ('randomForest', 'Random Forest', 1);
INSERT INTO Algorithms (identifier, description, active) VALUES ('sgd', 'Vanilla Stochastic Gradient Descent', 1);
INSERT INTO Algorithms (identifier, description, active) VALUES ('svm', 'Support Vector Machine', 1);